[book]
authors = ["Martin Geisler"]
language = "en"
multilingual = false
src = "src"
title = "Comprehensive Rust ðŸ¦€"

[rust]
edition = "2021"

[build]
extra-watch-dirs = ["po"]

[preprocessor.links]
renderers = ["html"]
before = ["gettext"]

[preprocessor.index]
renderers = ["html"]

[preprocessor.svgbob]
renderers = ["html"]
after = ["gettext"]
class = "bob"

# Enable this preprocessor to overlay a large red rectangle on the
# pages. This will show you an estimate of what the course
# participants can see during the presentation.
#
# [preprocessor.aspect-ratio-helper]
# command = "./aspect-ratio-helper.py"

[output.html]
curly-quotes = true
additional-js = ["ga4.js", "speaker-notes.js"]
additional-css = ["svgbob.css", "speaker-notes.css", "language-picker.css"]
site-url = "/comprehensive-rust/"
git-repository-url = "https://github.com/google/comprehensive-rust"
edit-url-template = "https://github.com/google/comprehensive-rust/edit/main/{path}"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true

[output.html.redirect]
"structure.html" = "running-the-course/course-structure.html"
"unsafe/unsafe-functions.html" = "calling-unsafe-functions.html"
