[workspace]
members = [
  "mdbook-exerciser",
  "mdbook-course",
  "src/exercises",
  "src/bare-metal/useful-crates/allocator-example",
  "src/bare-metal/useful-crates/zerocopy-example",
  "src/exercises/concurrency/chat-async",
]
