# Please use a nightly rustfmt for these settings.
unstable_features = true
imports_granularity = "Module"
wrap_comments = true

# The code blocks get a scrollbar if they are wider than this.
max_width = 85
# Allow all constructs to take up max_width columns.
use_small_heuristics = "Max"
