[package]
name = "sync-exercises"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "dining-philosophers"
path = "dining-philosophers.rs"

[[bin]]
name = "link-checker"
path = "link-checker.rs"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking"] }
scraper = "0.22.0"
thiserror = "2.0.11"

[dev-dependencies]
tempfile = "3.14.0"
