[workspace]

[package]
name = "rtc"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
aarch64-paging = { version = "0.10.0", default-features = false }
aarch64-rt = "0.2.2"
arm-gic = "0.7.1"
arm-pl011-uart = "0.3.2"
bitflags = "2.9.4"
chrono = { version = "0.4.42", default-features = false }
log = "0.4.28"
safe-mmio = "0.2.5"
smccc = "0.2.2"
spin = "0.10.0"
zerocopy = "0.8.27"
