[workspace]

[package]
name = "rtc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aarch64-rt = "0.1.3"
arm-gic = "0.4.0"
bitflags = "2.9.0"
chrono = { version = "0.4.41", default-features = false }
log = "0.4.27"
smccc = "0.2.1"
spin = "0.10.0"
