[package]
name = "i18n-helpers"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.68"
mdbook = "0.4.25"
polib = "0.1.0"
pulldown-cmark = { version = "0.9.2", default-features = false }
semver = "1.0.16"
serde_json = "1.0.91"
toml = "0.5.1"
