[package]
name = "chat-async"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = { version = "0.3.31", features = ["sink"] }
http = "1.3.1"
tokio = { version = "1.47.1", features = ["full"] }
tokio-websockets = { version = "0.12.3", features = ["client", "fastrand", "server", "sha1_smol"] }
