[workspace]

[package]
name = "alloc-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
buddy_system_allocator = "0.11.0"
panic-halt = "1.0.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
